# Generated by Django 3.2 on 2022-05-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
