# Generated by Django 3.2 on 2022-05-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_remove_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
