###############################################################################
"""
Django settings for django_pp4_ci_wqcs project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
# IMPORTED RESOURCES #

# EXTERNAL:
from pathlib import Path
import os
import dj_database_url
if os.path.isfile('env.py'):
    import env

###############################################################################


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

###############################################################################
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 0
# SET TO 0 POR PRODUCTION!
###############################################################################

ALLOWED_HOSTS = [
    'django_pp4_ci_wqcs.herokuapp.com',
    'pp4-ci-wqcs.herokuapp.com',
    'https://pp4-ci-wqcs.herokuapp.com/',
    'localhost',
    '8080-moccasin-canidae-gedulbh4.ws-us28.gitpod.io',
    '8080-moccasin-canidae-gedulbh4.ws-us29.gitpod.io',
    '8080-moccasin-canidae-gedulbh4.ws-us30.gitpod.io',
    '8080-moccasin-canidae-gedulbh4.ws-us31.gitpod.io',
    '8080-moccasin-canidae-gedulbh4.ws-us32.gitpod.io',
    '8080-moccasin-canidae-gedulbh4.ws-us33.gitpod.io',
    '8080-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us28.gitpod.io',
    '8080-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us29.gitpod.io',
    '8080-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us30.gitpod.io',
    '8080-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us31.gitpod.io',
    '8080-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us32.gitpod.io',
    '8080-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us33.gitpod.io'
]

# Just for Django version 4; solved with the help of
# Code Institute Tutor Assistance (Alan) on December 20th, 2021
# at 15:55 (with first element, other added later)

CSRF_TRUSTED_ORIGINS = [
    'https://pp4-ci-wqcs.herokuapp.com/',
    'localhost',
    'https://8000-moccasin-canidae-gedulbh4.ws-us25.gitpod.io',
    'https://8000-moccasin-canidae-gedulbh4.ws-us26.gitpod.io',
    'https://8000-moccasin-canidae-gedulbh4.ws-us27.gitpod.io',
    'https://8000-moccasin-canidae-gedulbh4.ws-us28.gitpod.io',
    'https://8000-moccasin-canidae-gedulbh4.ws-us29.gitpod.io',
    'https://8000-moccasin-canidae-gedulbh4.ws-us30.gitpod.io',
    'https://8000-moccasin-canidae-gedulbh4.ws-us31.gitpod.io',
    'https://8000-moccasin-canidae-gedulbh4.ws-us32.gitpod.io',
    'https://8000-moccasin-canidae-gedulbh4.ws-us33.gitpod.io',
    'https://8000-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us28.gitpod.io/',
    'https://8000-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us29.gitpod.io/',
    'https://8000-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us30.gitpod.io/',
    'https://8000-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us31.gitpod.io/',
    'https://8000-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us32.gitpod.io/',
    'https://8000-csc7-pp4ciwqcs-nx9o6gmef7u.ws-us33.gitpod.io/'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'django_summernote',
    'crispy_forms',
    'app_instructions',
    'app_weather',
    'app_contact',
    'app_blog',
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_pp4_ci_wqcs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_pp4_ci_wqcs.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(os.environ.get('DATABASE_URL')),
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
   'NAME':
   'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
   'NAME':
   'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
   'NAME':
   'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
   'NAME':
   'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_STORAGE = (
    'cloudinary_storage.storage.StaticHashedCloudinaryStorage'
)
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
