# Generated by Django 4.0 on 2022-01-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAndTimeForData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=200)),
                ('time', models.TimeField(default='00:00:00', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WindData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed', models.FloatField(max_length=200)),
                ('wind_direction', models.FloatField(max_length=200)),
                ('wind_rec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_weather.dataandtimefordata')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(max_length=200)),
                ('feels_like', models.FloatField(max_length=200)),
                ('temperature_max', models.FloatField(max_length=200)),
                ('temperature_min', models.FloatField(max_length=200)),
                ('temp_rec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_weather.dataandtimefordata')),
            ],
        ),
        migrations.CreateModel(
            name='OtherWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(max_length=200)),
                ('humidity', models.FloatField(max_length=200)),
                ('visibility', models.FloatField(max_length=200)),
                ('sky', models.CharField(max_length=200)),
                ('main', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('sunrise', models.CharField(max_length=200)),
                ('sunset', models.CharField(max_length=200)),
                ('other_rec', models.ForeignKey(default=352, on_delete=django.db.models.deletion.CASCADE, to='app_weather.dataandtimefordata')),
            ],
        ),
    ]
