# Generated by Django 4.0 on 2022-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winddata',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='winddata',
            name='wind_direction',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='winddata',
            name='wind_speed',
            field=models.CharField(max_length=200),
        ),
    ]
