# Generated by Django 4.0 on 2022-01-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_weather', '0002_alter_winddata_date_alter_winddata_wind_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winddata',
            name='wind_direction',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='winddata',
            name='wind_speed',
            field=models.FloatField(max_length=200),
        ),
    ]
