# Generated by Django 4.0 on 2022-01-04 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_weather', '0003_alter_winddata_wind_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherweatherdata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 4, 22, 31, 56, 737704), max_length=200),
        ),
        migrations.AddField(
            model_name='temperaturedata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 4, 22, 31, 56, 737087), max_length=200),
        ),
        migrations.AddField(
            model_name='winddata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 4, 22, 31, 56, 736475), max_length=200),
        ),
        migrations.AlterField(
            model_name='winddata',
            name='date',
            field=models.DateField(max_length=200),
        ),
    ]
