# Generated by Django 4.0 on 2022-01-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_weather', '0006_alter_otherweatherdata_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherweatherdata',
            name='time',
            field=models.TimeField(default='00:00:00', max_length=200),
        ),
        migrations.AlterField(
            model_name='temperaturedata',
            name='time',
            field=models.TimeField(default='00:00:00', max_length=200),
        ),
        migrations.AlterField(
            model_name='winddata',
            name='time',
            field=models.TimeField(default='00:00:00', max_length=200),
        ),
    ]
